### ISSUE TITLE
Current status of Zinc, or what are the "must have's" before stable release

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#212]
I've had a discussion with @eed3si9n about what's currently missing in Zinc. I want to share this information here so that interested contributors can have a view of the current status of the project.

- [x] Fix handling of anonymous and local classes defined in Java. #86. Fix [here](https://github.com/sbt/zinc/pull/217).
- [x] Honor as seen from correctly for inherited classes (current Zinc is undercompiling). @gkossakowski has talked about this [here](https://github.com/sbt/zinc/pull/86), [here](https://github.com/sbt/sbt/issues/1104) and [here](https://github.com/sbt/zinc/issues/174).
- [x] Refine the Java binary compatible API that build tools can use (Gradle, Pants, SBT, Bazel). https://github.com/sbt/zinc/blob/1.0/internal/compiler-interface/src/main/java/xsbti/compile/IncrementalCompiler.java https://github.com/sbt/zinc/issues/79
  
After finishing up the work on class-deps and the name-hashed algorithm, there would be some benchmarking involved to assess the real speedup on medium-to-large codebases.
Eugene has said that he could work on item 3 while others tackle 1 and 2, which require some knowledge on scalac internals.
  
After these items are finished, there will be a beta version that people can depend on and try. Given the modularity among Zinc and the build tools, it is possible for Scala teams to assess the benefits of the algorithm by:

* Cloning latest master
* In your checkout, running sbt publishLocal
* In your sbt project changing version to 0.13.12-SNAPSHOT and running sbt normally.

**Comment by jvican** [comment]
It would be great if @gkossakowski can confirm this list of missing tasks.

**Comment by smarter** [comment]
> Honor as seen from correctly for inherited classes (current Zinc is undercompiling).

This issue has always been present in sbt incremental compiler and is still present in the 0.13 branch and in the 1.0 branch (except if you use dotty, which has its own [fixed compiler bridge](https://github.com/sbt/zinc/issues/174#issuecomment-247002607)), so it should not be a blocker for a stable release.

**Comment by smarter** [comment]
> Create a Java binary compatible API that build tools can use (Gradle, Pants, SBT, Bazel). 

Are you also going to patch sbt 0.13 so that it can optionally use zinc? (Note that sbt 1.0 already depends on zinc, and that the only reason these changes were not backported to the sbt 0.13 incremental compiler is that they would break binary compatibility)

**Comment by jvican** [comment]
> This issue has always been present in sbt incremental compiler and is still present in the 0.13 branch and in the 1.0 branch (except if you use dotty, which has its own fixed compiler bridge), so it should not be a blocker for a stable release.
  
When Zinc is released, we'd like to promise 2 years of binary compatibility at least. Even though this is an issue present in previous Zinc versions, it has a great effect in the correctness of the incremental compiler and we should aim at 100% correctness if possible before a stable release.
  
> Are you also going to patch sbt 0.13 so that it can optionally use zinc? (Note that sbt 1.0 already depends on zinc, and that the only reason these changes were not backported to the sbt 0.13 incremental compiler is that they would break binary compatibility)
  
Don't know yet :smile:. I'll see whether this is a feasible option in the future.

**Comment by smarter** [comment]
> When Zinc is released, we'd like to promise 2 years of binary compatibility at least. Even though this is an issue present in previous Zinc versions, it has a great effect in the correctness of the incremental compiler and we should aim at 100% correctness if possible before a stable release.

I don't think fixing this issue will have any consequence on binary compatibility.

**Comment by smarter** [comment]
> Don't know yet :smile:. I'll see whether this is a feasible option in the future.

It seems to me your time might be better spent in trying to get sbt 1.0 ready (which means creating some sort of compatibility layer for 0.13 code to work with sbt 1.0) instead, since it already has everything you need.

**Comment by jvican** [comment]
> I don't think fixing this issue will have any consequence on binary compatibility.
  
I don't know, but I wouldn't like to hypothesize. @eed3si9n and I agree that these are blockers for a stable release.
  
> It seems to me your time might be better spent in trying to get sbt 1.0 ready (which means creating some sort of compatibility layer for 0.13 code to work with sbt 1.0) instead, since it already has everything you need.
  
Good suggestion, but the Scala Center has already agreed to have a look at Zinc and fix these issues as soon as possible so that not only sbt, but all the other build tools available in our community, can benefit from it.
  
If you think this is a priority that the Scala Center should have, please feel free to [write an Advisory Board proposal](https://github.com/scalacenter/advisoryboard) and forward it to Bill Venners.

**Comment by smarter** [comment]
> I don't know, but I wouldn't like to hypothesize. @eed3si9n and I agree that these are blockers for a stable release.

Are other undercompilation issues considered blockers or just this one? I'm thinking of https://github.com/sbt/zinc/issues/101 for example, which affects the API of zinc, but it might not affect the "Java binary compatible API that build tools can use" you plan to build if it's high-level enough.

**Comment by smarter** [comment]
In fact, I would very much like you to expand on what exactly will be part of the the stable API you mentioned. I was planning to work with a student on fixing the various issues in zinc I reported last year (https://github.com/sbt/zinc/issues/created_by/smarter), this cannot be done without changing the API of zinc, so we need to make sure that these APIs are considered internal/unstable or that the issues get fixed first (but bear in mind that once zinc 1.0 actually gets used, many more issues might be reported and fixing them might affect the API too)

**Comment by romanowski** [comment]
What will be consider API of zinc? Interfaces for end users? Analysis formats? Behavior of incremental compilation?

Internally we've got a lot of work on zinc and I want to know deadline for PRs :)

Generally cleaning up API and making it stable (or at least minimal part) is really good idea

**Comment by romanowski** [comment]
@eed3si9n @dwijnand I we might use zinc gitter channel (especially if zinc will become something more then internal sbt dependency).

**Comment by jvican** [comment]
> In fact, I would very much like you to expand on what exactly will be part of the the stable API you mentioned. 
  
I'll work on that with @eed3si9n when the correctness of the compiler is up to a level that deserves a stable release. I don't know details of how this API will look like yet.
  
> Are other undercompilation issues considered blockers or just this one?
  
Ideally, all of them. I'll try to work on them so that Zinc can have a beta out before 28th February.
  
> What will be consider API of zinc? Interfaces for end users? Analysis formats? Behavior of incremental compilation?
  
Yet to be decided, but I'll be making PRs soon -- I've just started to hack on this. I agree that it's good that we all decide how that API should look like, so I'm happy to chat about it either here or in Gitter. However, I'll leave the API design until the end since my priority is to complete Grzgorz's algorithm.

**Comment by gkossakowski** [comment]
Hi,
The list of remaining tasks for zinc's 1.0 release looks complete to me. I thought I'd give you guys estimates of how much work will it take to fix them:

  - _Fix handling of anonymous and local classes defined in Java. #86_ -- 60 hours
  - _Honor as seen from correctly for inherited classes (current Zinc is undercompiling)._ -- 200 hours
  - _Create a Java binary compatible API that build tools can use (Gradle, Pants, SBT, Bazel)._ -- 160 hours

Total: 420 hours ~ 2.5 months of full time work of a single person. My estimates are for a person already familiar with zinc/incremental compilation.

It's true that undercompiling in case of inheritance is already an issue but class-based deps make the issue more pressing. More granular dependency tracking creates more opportunities for undercompilation to pop up in real life scenarios.

**Comment by gkossakowski** [comment]
I might be able to help with bazel integration because we use bazel at Stripe. I will have time to look at it only in March, though.

**Comment by stuhood** [comment]
And the pantsbuild/pants project is happy to contribute as well.

**Comment by jvican** [comment]
I would probably contact you when I'm defining the public API of the compiler. We'll need the help of other build tools to spot "hot" use cases. @stuhood @gkossakowski 
  
By the way, handling of anonymous and local classes in Java is already [fixed](https://github.com/sbt/zinc/pull/217). This is my first PR to Zinc so I'll be happy if someone has a look at it.

**Comment by romanowski** [comment]
@jvican I think I can help with gradle and intellij

**Comment by eed3si9n** [comment]
As a general note, I'm open to discuss that the must-have lists are.

@smarter  wrote:

> In fact, I would very much like you to expand on what exactly will be part of the the stable API you mentioned.

For the Zinc API, sbt would need things like compilation, docs, and REPL.
I think it would be nice if we can get abstraction of the REPL so it can be driven programmatically. See https://github.com/sbt/zinc/issues/170
What I would *not* promise as the Zinc API point would be any implementation detail of how we keep track of incrementality, including `Analysis` and its text representation.

Also, now that @romanowski has sent the cached compilation PR (https://github.com/sbt/zinc/pull/216), Zinc might as well embrace Bazel/Pants caching and try to make Analysis machine independent - https://github.com/sbt/zinc/issues/218

**Comment by dwijnand** [comment]
Older Java API discussion: https://github.com/sbt/zinc/issues/79

**Comment by stuhood** [comment]
> and try to make Analysis machine independent

This would be handy, as currently we do our own rewriting of the analysis file for portability.

**Comment by jvican** [comment]
We're done with this. The Scala Center will continue to pour some resources into Zinc, so we will follow up on some improvements to the Zinc algorithm and the binary API.
