### ISSUE TITLE
Design a Java-friendly, safe Zinc API for build tools

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#300]
This is an umbrella ticket for the Zinc API design.
  
I want it to include:
- [ ] Design of Java-friendly API: https://github.com/sbt/zinc/issues/79.
- [x] Fast serialization of analysis files: https://github.com/sbt/zinc/issues/268 | https://github.com/sbt/zinc/issues/203.
- [x] Make analysis content machine-independent: https://github.com/sbt/zinc/issues/218, per @stuhood's request.

Possible tickets if there's time:
  
- [ ] Add built-in support for running Zinc on the background: https://github.com/sbt/zinc/issues/299.
- [ ] Add support for incremental testing: https://github.com/sbt/zinc/issues/265.
- [ ] Add support for test discovery? I would like to see if there's something we should internalize in Zinc, I have a feeling some functionality should be built into Zinc public APIs for: https://github.com/sbt/sbt-testng, https://github.com/sbt/junit-interface, et cetera.
  
I'll comment on my goals behind the API later on.

**Comment by eed3si9n** [comment]
Given that RC-1 is coming up soon, could we reduce the items on this list, and focus on getting a clean Zinc API that doesn't require access to internal?
If you don't have time for it, I'd be happy to take it on.

**Comment by jvican** [comment]
I am already working on all this, and yeah, some items on the list will disappear if there's not enough time.

**Comment by jvican** [comment]
I've had a look at [Pants' Zinc integration](https://github.com/pantsbuild/pants/tree/master/src/scala/org/pantsbuild/zinc) to identify which internal API they're using.
  
It seems that the integration is not up-to-date with the utils we've added in our first Zinc API iteration. If those are solved, these are the things that we should provide to Pants so that there's no internal dependency:
  
- [ ] Provide default implementation of `DefinesClass` (located in `Locate.scala`).
- [ ] Provide way to create `xsbti.compile.SingleOutput` and `xsbti.compile.MultipleOutput`.
- [ ] Provide way to get hold of `JavaTools` (in `ZincCompilerUtil`).
- [ ] Provide way to get hold of an instance of `Compilers` that has both `AnalyzingCompiler` and `JavaAnalyzingCompiler`.
  
The first item `DefinesClass` needs to be done in a new interface, since we cannot implement it where it's defined (the compiler interface). Removing it from there is not an option either: `PerClasspathEntryLookup` and `Setup` depend on it.
  
Aside from these, only https://github.com/sbt/zinc/issues/312 is missing.

**Comment by eed3si9n** [comment]
"Provide X" is strictly addition of functions so we can do this post 1.0, correct?

**Comment by stuhood** [comment]
@jvican : To be clear, https://github.com/pantsbuild/pants/pull/4728 contains the changes to incorporate https://github.com/sbt/zinc/pull/325 and https://github.com/sbt/zinc/pull/351 ... master is on `X7`.

**Comment by jvican** [comment]
@stuhood Yeah, I was interested to see how close you're from only public API after my changes to the loggers. But thanks for the heads up.
  
@eed3si9n Yeah, as discussed in Gitter, we will merge those improvements in RC-2.

**Comment by eed3si9n** [comment]
Builder pattern (zero-arg ctor) for configuration object should also be added to this list.

**Comment by jvican** [comment]
FWIW, this is already done.

**Comment by yawaramin** [comment]
This appears to be the new Java API, for those looking for it: https://github.com/sbt/zinc/blob/9bef954753a1ae033722d5bc9e89b945a9f2da3e/zinc/src/main/java/xsbti/compile/ZincCompilerUtil.java
