### ISSUE TITLE
Epic: Integrate changes in mspnf/zinc

### ISSUE THREAD

**Issue by dwijnand** [sbt/zinc#777]
* [x] [Build pipelining][1] (also scala/scala-dev#643) #744
  * [x] changes to the `InvalidationProfiler` (not the `synchronized`s) [[`545c917` (#744)](https://github.com/sbt/zinc/pull/744/commits/545c917961589b7f1356fc4bb128435273a07c0c) ](https://github.com/sbt/zinc/pull/744/commits/545c917961589b7f1356fc4bb128435273a07c0c)
  * [x] ~cancellation: Zinc users need access to nsc's `reporter.cancelled = true`~ (`advance` is sufficient)
* [x] [Referentially transparent (RT) builds][2]
	* [x] #782 allow paths to be mapped so that artifacts read from analyses match those on the compilation classpath
    * [x] quickApi / provenance
      * [x] extend existing `Lookup` api (which is already customizable) to include `lookupAnalyzedClass` #785
      * [x] add provenance to AnalyzedClass #786
    * [x] ~override
`ExternalHooks#hashClassPath` to compute `FileHash` directly from the file names~ (nothing TODO, already available since #427)
* [x] [Virtual source files][3] #712
* [x] [Additional changes][4]
  * [x] SafeLazy concurreny issue #740
  * [x] ~optimized UsedName's scopes~ #764 (postponed)
  * [x] ~`Map<String, Object extraHooks()` + `Hooks` methods to set and retrieve specific hooks and callbacks~ (this was for expediency, replace with typed API additions
  * [x] Make hashing childrenOfSealedClass stable #788
* [x] ~additional [performance](https://github.com/sbt/zinc/issues?q=sort:updated-desc+is:open+label:performance) tickets~ (postponed)

original diff: https://github.com/sbt/zinc/compare/develop...mspnf:1.3.x-contrib?w=1 ([formatted](https://github.com/sbt/zinc/compare/develop...dwijnand:1.3.x-formatted))

[1]: https://github.com/mspnf/zinc/blob/1.3.x-contrib/README-MORGANSTANLEY.MD#changes-related-to-pipelining
[2]: https://github.com/mspnf/zinc/blob/1.3.x-contrib/README-MORGANSTANLEY.MD#changes-related-to-rt-build
[3]: https://github.com/mspnf/zinc/blob/1.3.x-contrib/README-MORGANSTANLEY.MD#changes-related-to-in-memory-source
[4]: https://github.com/mspnf/zinc/blob/1.3.x-contrib/README-MORGANSTANLEY.MD#additional-changes

**Comment by dwijnand** [comment]
Done.  The remaining additional changes will follow on (or not, as they're looked at 1 by 1).
